version: "3.4"
services:
  sample-app:
    container_name: sample-app
    working_dir: /app
    volumes:
      - "./certificates:/app/certificates"
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    command: "dotnet SampleApp.Web.dll"
    ports:
      - "80:80"
      - "443:443"

  terraform:
    container_name: terraform
    working_dir: /infra-as-code
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.terraform
    volumes:
      - "./terraform:/infra-as-code"
      - "./scripts/plan-and-apply.sh:/scripts/plan-and-apply.sh"
    command: bash "../scripts/plan-and-apply.sh"

  auth0-cli:
    container_name: auth0-cli
    working_dir: /infra-as-code
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.auth0-cli
    volumes:
      - "./auth0-cli:/infra-as-code"
    command: "a0deploy import --config_file config.json --input_file ."

  pulumi:
    container_name: pulumi
    working_dir: /infra-as-code
    env_file:
      - .env
    image: pulumi/pulumi-dotnet
    volumes:
      - "./pulumi/PulumiSample:/infra-as-code"
    command: "pulumi up --yes --stack PulumiSample --non-interactive"
